language: node_js
node_js:
  - lts/*

cache:
  directories:
    - node_modules

before_install:
  - export TZ='Asia/Shanghai'

install:
  - npm install hexo-cli -g
  - npm install https://github.com/CodeFalling/hexo-asset-image -—save
  - npm install

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "miaochiahao"
  - git config user.email "miaochiahao@gmail.com"
  - git add .
  - git commit -m "Travis CI Auto Builder at $(date +'%Y-%m-%d %H:%M:%S')"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

branches:
  only:
    - blog_source
